// Real Minecraft server profiles extracted from internet scan data (deduped by ip+port).
// Persona generation samples whole profiles so version/MOTD/slots/favicon/timezone are authentic
// combinations observed in the wild, not independently-random fields.

export interface ServerProfile {
	readonly versionName: string;
	readonly protocol: number;
	readonly motd: string;
	readonly maxPlayers: number;
	readonly online: number;
	readonly hasFavicon: boolean;
	readonly enforcesSecureChat: boolean;
	readonly port: number;
	readonly utcOffsetMinutes: number;
	readonly country: string;
}

export const PERSONA_CORPUS: readonly ServerProfile[] = [
  {
    "versionName": "Purpur 1.21.11",
    "protocol": 774,
    "motd": "ᴘᴏᴡᴇʀᴇᴅ ʙʏ ғʀᴏɢɢʏᴄᴏʀᴇ",
    "maxPlayers": 800,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25612,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 540,
    "country": "JP"
  },
  {
    "versionName": "Paper 26.2",
    "protocol": 776,
    "motd": "The adventure continues",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Velocity 1.7.2-26.1.2",
    "protocol": 774,
    "motd": "DoubleShotTom\nJoin Us!",
    "maxPlayers": 500,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "1.19.2",
    "protocol": 760,
    "motd": "A Minecraft Server",
    "maxPlayers": 10,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25642,
    "utcOffsetMinutes": 0,
    "country": "NL"
  },
  {
    "versionName": "§x§2§e§7§e§f§f§l0/100",
    "protocol": 774,
    "motd": "         ᴘʀᴏᴊᴇᴄᴛ ᴘᴀѕѕɪᴏɴ ѕᴇʀᴠᴇʀ (1.21.11)",
    "maxPlayers": 100,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.8",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25615,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Amethyst season 6!",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 120,
    "country": "LV"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "Sids Squad Server",
    "maxPlayers": 8,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "Velocity 1.7.2-26.1.1",
    "protocol": 774,
    "motd": "Helios",
    "maxPlayers": 500,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 120,
    "country": "FI"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "craft.minezerver.de",
    "maxPlayers": 6,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Postapok: IDK",
    "maxPlayers": 50,
    "online": 1,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25600,
    "utcOffsetMinutes": 180,
    "country": "RU"
  },
  {
    "versionName": "Purpur 26.1.2",
    "protocol": 775,
    "motd": "Guzzarna ba löper",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 120,
    "country": "FI"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "MineMinions",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "Paper 1.21.5",
    "protocol": 770,
    "motd": "Gott im himmel",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -0,
    "country": "GB"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25566,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "All the Mods 10",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.21.10",
    "protocol": 773,
    "motd": "LovCraft SMP ❤",
    "maxPlayers": 30,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -480,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "CH"
  },
  {
    "versionName": "1.21.5",
    "protocol": 770,
    "motd": "Le communisme de l'ambiance",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "Folia 1.21.11",
    "protocol": 774,
    "motd": "LegendaryHardcore",
    "maxPlayers": 100,
    "online": 20,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "⚔ Adventure Coin World ⚔ Explore • Fight • Earn • Upgrade Quests • Dungeons • Skills • Economy Forge your legend. Coins are power.",
    "maxPlayers": 100,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 2,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25555,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25510,
    "utcOffsetMinutes": -0,
    "country": "GB"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "All the Mods 10",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25595,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "Grab your Ass and Spread 'em",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25593,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "WELCOME TO THE ISLAND",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "CA"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "SE"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "Welcome!",
    "maxPlayers": 30,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "GB"
  },
  {
    "versionName": "Velocity 1.7.2-26.1.2",
    "protocol": 774,
    "motd": "A Velocity Server",
    "maxPlayers": 500,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "Paper 1.21.10",
    "protocol": 773,
    "motd": "Build Server",
    "maxPlayers": 5,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25566,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "Purpur 1.21.11",
    "protocol": 774,
    "motd": "Season 6 (VOICECHAT)",
    "maxPlayers": 4,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "NL"
  },
  {
    "versionName": "26.1",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 5,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "JP"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 180,
    "country": "RU"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Welcome to SoucheVille",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DK"
  },
  {
    "versionName": "1.21.10",
    "protocol": 773,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Server de mine",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "DE"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "DE"
  },
  {
    "versionName": "1.16.5",
    "protocol": 754,
    "motd": "Valhelsia 3 Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -0,
    "country": "GB"
  },
  {
    "versionName": "1.19.2",
    "protocol": 760,
    "motd": "A Minecraft Server",
    "maxPlayers": 5,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25636,
    "utcOffsetMinutes": 0,
    "country": "NL"
  },
  {
    "versionName": "Paper 26.2",
    "protocol": 776,
    "motd": "404",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 120,
    "country": "TR"
  },
  {
    "versionName": "Paper 26.2",
    "protocol": 776,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "Minecraft Legendary Edition",
    "maxPlayers": 10,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "RU"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "All the Mods 10",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "SE"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 30,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25585,
    "utcOffsetMinutes": 120,
    "country": "RO"
  },
  {
    "versionName": "Spigot 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.11",
    "protocol": 774,
    "motd": "Vanilla 1.21.11",
    "maxPlayers": 7,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "DE"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "sung sung sung tahur",
    "maxPlayers": 67,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "EnderHub",
    "maxPlayers": 100,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25567,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "A Minecraft Server",
    "maxPlayers": 10,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "CA"
  },
  {
    "versionName": "UniverseSpigot 1.21.8",
    "protocol": 772,
    "motd": "Another MOTD\nmuch wow",
    "maxPlayers": 200,
    "online": 30,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "kpzip's minecraft server\nmc.kpzip.xyz",
    "maxPlayers": 100,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -480,
    "country": "US"
  },
  {
    "versionName": "1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 60,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "CN"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "CN"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 540,
    "country": "JP"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "\"Welcome to Alex's Server!\"",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 600,
    "country": "AU"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -420,
    "country": "US"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "CREEPERS! ILLAGERS!",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Cobblemon Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "The Nest\nBuild your home. Forge your story.",
    "maxPlayers": 69,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "GB"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "A Paper Minecraft Server powered by Docker",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "26.2",
    "protocol": 776,
    "motd": "pit-axe ┃ survival · terralith · fabric",
    "maxPlayers": 5,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.19.4",
    "protocol": 762,
    "motd": "Minecraft Survival Modded",
    "maxPlayers": 12,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25625,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "Velocity 1.7.2-26.1.2",
    "protocol": 774,
    "motd": "                     Minezone [1.8-26.1]\n            SCB - HUGE CLASSES REVAMP!",
    "maxPlayers": 1,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "Staff",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25571,
    "utcOffsetMinutes": 0,
    "country": "CA"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 774,
    "motd": "MC",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "Paper 26.2",
    "protocol": 774,
    "motd": "Dingle",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -420,
    "country": "US"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "landia",
    "maxPlayers": 10,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Werbung",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "Paper 26.2",
    "protocol": 776,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 540,
    "country": "JP"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "miso land | season 1\nbruhhhhhh we crafting",
    "maxPlayers": 8,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "CA"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "Ich gehe lieber auf DuBix.net",
    "maxPlayers": 420,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "JP"
  },
  {
    "versionName": "1.19.2",
    "protocol": 760,
    "motd": "A Minecraft Server",
    "maxPlayers": 2,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.20.6",
    "protocol": 766,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "JP"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "JP"
  },
  {
    "versionName": "1.8.9",
    "protocol": 47,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "JP"
  },
  {
    "versionName": "1.21.11",
    "protocol": 774,
    "motd": "Hello PB gang",
    "maxPlayers": 15,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25545,
    "utcOffsetMinutes": 600,
    "country": "AU"
  },
  {
    "versionName": "Purpur 1.21.10",
    "protocol": 773,
    "motd": "Smart-Minecraft v1.2.6",
    "maxPlayers": 500,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.10",
    "protocol": 773,
    "motd": "Me, Myself, and I",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25578,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "Boom Boom Boom!",
    "maxPlayers": 30,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "26.1",
    "protocol": 775,
    "motd": "4Netplayers M&L",
    "maxPlayers": 4,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -480,
    "country": "US"
  },
  {
    "versionName": "Spigot 1.21.5",
    "protocol": 770,
    "motd": "A Minecraft Server",
    "maxPlayers": 2115,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "PL"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 4,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "A Minecraft Server",
    "maxPlayers": 32,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "IL"
  },
  {
    "versionName": "1.21.10",
    "protocol": 773,
    "motd": "Heiko und Chris",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "DE"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "BurrMods Server",
    "maxPlayers": 30,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "AT"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "Pedilo",
    "maxPlayers": 8,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "AR"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "🔥 CONSTRUA SUA HISTÓRIA 🔥\n⚒ Junte-se, sobreviva e evolua com seus amigos",
    "maxPlayers": 50,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -180,
    "country": "BR"
  },
  {
    "versionName": "26.1.2",
    "protocol": 775,
    "motd": "Minecraft Fabric",
    "maxPlayers": 24,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.10",
    "protocol": 773,
    "motd": "Server for Kobriis ONLY!",
    "maxPlayers": 20,
    "online": 1,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "CZ"
  },
  {
    "versionName": "",
    "protocol": 774,
    "motd": "            ｢ ᴡʜɪᴛᴇʀɪsᴇ • ноʙый ᴄᴇзон ｣\n       🏹 ɢʀɪᴇꜰ, sᴍᴘ, ᴀɴᴀʀᴄʜʏ | 1.16 - 1.21.+ 🗡",
    "maxPlayers": 1337,
    "online": 175,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 120,
    "country": "RU"
  },
  {
    "versionName": "Purpur 1.21.11",
    "protocol": 774,
    "motd": "Rein in die Mine!",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "Paper 26.2",
    "protocol": 776,
    "motd": "                  Pride Month is OVER.\n         You are no longer allowed to be gay.",
    "maxPlayers": 67,
    "online": 1,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 774,
    "motd": "Insane Asylum",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "1.21",
    "protocol": 767,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25633,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.21.11",
    "protocol": 774,
    "motd": "Powered by AMP",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25570,
    "utcOffsetMinutes": 480,
    "country": "AU"
  },
  {
    "versionName": "1.21.10",
    "protocol": 773,
    "motd": "The Hole is the Goal",
    "maxPlayers": 15,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Welcome to Imaginescape",
    "maxPlayers": 20,
    "online": 1,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25575,
    "utcOffsetMinutes": -480,
    "country": "CA"
  },
  {
    "versionName": "Paper 1.21.10",
    "protocol": 773,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "A Cobblemon Academy Server",
    "maxPlayers": 10,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "SIMP",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "US"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "All the Mods 10",
    "maxPlayers": 9999,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "1.20.1",
    "protocol": 763,
    "motd": "BVMC 2.0",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": -360,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "ValerianSMP",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "FR"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": -300,
    "country": "CA"
  },
  {
    "versionName": "Spigot 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 10,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "Paper 1.21.11",
    "protocol": 774,
    "motd": "Kill the snitch, and we will let you out",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "US"
  },
  {
    "versionName": "Paper 26.1.2",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 60,
    "country": "DE"
  },
  {
    "versionName": "1.21.1",
    "protocol": 767,
    "motd": "Fette Kinder AG",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "DE"
  },
  {
    "versionName": "Paper 1.20.1",
    "protocol": 763,
    "motd": "⚔ SIMPLE SERVER ⚔",
    "maxPlayers": 1000,
    "online": 0,
    "hasFavicon": true,
    "enforcesSecureChat": false,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "DE"
  },
  {
    "versionName": "26.1.1",
    "protocol": 775,
    "motd": "A Minecraft Server",
    "maxPlayers": 20,
    "online": 0,
    "hasFavicon": false,
    "enforcesSecureChat": true,
    "port": 25565,
    "utcOffsetMinutes": 0,
    "country": "JP"
  }
]
;
