import { z } from "zod";

/** What the client wanted. `legacy` = pre-1.7 0xFE ping; `unknown` = unparseable/abnormal. */
export const IntentKind = z.enum(["status", "login", "transfer", "legacy", "unknown"]);
export type IntentKind = z.infer<typeof IntentKind>;

/**
 * One captured connection attempt. `eventId` is generated by the daemon so the server can dedupe
 * retried batches idempotently. `observedAt` is the daemon's clock (informational only — the server
 * stamps its own receive time as authoritative because cheap VPS clocks drift).
 */
export const ConnectionEvent = z.object({
	eventId: z.string().uuid(),
	observedAt: z.string().datetime(),
	srcIp: z.string().min(1).max(45),
	srcPort: z.number().int().min(0).max(65535),
	protocolVersion: z.number().int().nullable(),
	serverAddress: z.string().max(512),
	serverPort: z.number().int().min(0).max(65535),
	intent: IntentKind,
	pingCompleted: z.boolean(),
	username: z.string().max(16).nullable(),
	playerUuid: z.string().max(36).nullable(),
	fingerprint: z.string().max(256).nullable(),
});
export type ConnectionEvent = z.infer<typeof ConnectionEvent>;
